import React, { Component } from 'react';
import { Add } from './Add';
import { Sequences } from './Sequences';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loadedSequences: [
        {
          "sequenceDescription": "Cloning vector pUC-JK, complete sequence",
          "sequenceName": "AF016541.1", "sequence": "TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATG"
        },
        {
          "sequenceDescription": "Cloning vector pSport2, complete sequence",
          "sequenceName": "U12391.1", "sequence": "CATTCGCCATTCAGGCTGCGCAACTGTTGGGAAGGGCGATCGGTGCGGGCCTCTTCGCTATTACGCCAGCTGGCGAAAGGGGGATGTGCTGCAAGGCGATTAAGTTGGGTAACGCCAGGGTTTTCCCAGTCACGACGTTGTAAAACGACGGCCAGTGAATTGAATTTAGGTGACACTATAGAAGAGCTATGACGTCGCATGCACGCGTACGTAAGCTTGGATCCTCTAGAGTCGACGAGCTCACTAGTGACAGCGGCCGCCCCGGGAATTCCGGACCGGTACCTGCAGGCGTACCAGCTTTCCCTATAGTGAGTCGTATTAGAGCTTGGCGTAATCATGGTCATAGCTGTTTCCTGTGTGAAATTGTTATCCGCTCACAATTCCACACAACATACGAGCCGGAAGCATAAAGTGTAAAGCCTGGGGTGCCTAATGAGTGAGCTAACTCACATTAATTGCGTTGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCCAGGGTGGTTTTTCTTTTCACCAGTGAGACGGGCAACAGCTGATTGCCCTTCACCGCCTGGCCCTGAGAGAGTTGCAGCAAGCGGTCCACGCTGGTTTGCCCCAGCAGGCGAAAATCCTGTTTGATGGTGGTTAACGGCGGGATATAACATGAGCTGTCTTCGGTATCGTCGTATCCCACTACCGAGATATCCGCACCAACGCGCAGCCCGGACTCGGTAATGGCGCGCATTGCGCCCAGCGCCATCTGATCGTTGGCAACCAGCATCGCAGTGGGAACGATGCCCTCATTCAGCATTTGCATGGTTTGTTGAAAACCGGACATGGCACTCCAGTCGCCTTCCCGTTCCGCTATCGGCTGAATTTGATTGCGAGTGAGATATTTATGCCAGCCAGCCAGACGCAGACGCGCCGAGACAGAACTTAATGGGCCCGCTAACAGCGCGATTTGCTGGTGACCCAATGCGACCAGATGCTCCACGCCCAGTCGCGTACCGTCTTCATGGGAGAAAATAATACTGTTGATGGGTGTCTGGTCAGAGACATCAAGAAATAACGCCGGAACATTAGTGCAGGCAGCTTCCACAGCAATGGCATCCTGGTCATCCAGCGGATAGTTAATGATCAGCCCACTGACCCGTTGCGCGAGAAGATTGTGCACCGCCGCTTTACAGGCTTCGACGCCGCTTCGTTCTACCATCGACACCACCACGCTGGCACCCAGTTGATCGGCGCGAGATTTAATCGCCGCGACAATTTGCGACGGCGCGTGCAGGGCCAGACTGGAGGTGGCAACGCCAATCAGCAACGACTGTTTGCCCGCCAGTTGTTGTGCCACGCGGTTGGGAATGTAATTCAGCTCCGCCATCGCCGCTTCCACTTTTTCCCGCGTTTTCGCAGAAACGTGGCTGGCCTGGTTCACCACGCGGGAAACGGTCTGATAAGAGACACCGGCATACTCTGCGACATCGTATAACGTTACTGGTTTCACATTCACCACCCTGAATTGACTCTCTTCCGGGCGCTATCATGCCATACCGCGAAAGGTTTTGCGCCATTCGATGGTGTCAACGTAAATGCCGCTTCGCCTTCGCGCGCGAATTGCAAGCTCTGCATTAATGAATCGGCCAACGCGCGGGGAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGGCTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAGGAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCAATGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGGACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGCCATAACTTCGTATAGCATACATTATACGAAGTTATGGCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGCCAGGGGTGGGCACACATATTTGATACCAGCGATCCCTACACAGCACATAATTCAATGCGACTTCCCTCTATCGCACATCTTAGACCTTTATTCTCCCTCCAGCACACATCGAAGCTGCCGAGCAAGCCGTTCTCACCAGTCCAAGACCTGGCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGAAATTGTAAACGTTAATATTTTGTTAAAATTCGCGTTAAATTTTTGTTAAATCAGCTCATTTTTTAACCAATAGGCCGAAATCGGCAAAATCCCTTATAAATCAAAAGAATAGACCGAGATAGGGTTGAGTGTTGTTCCAGTTTGGAACAAGAGTCCACTATTAAAGAACGTGGACTCCAACGTCAAAGGGCGAAAAACCGTCTATCAGGGCGATGGCCCACTACGTGAACCATCACCCTAATCAAGTTTTTTGGGGTCGAGGTGCCGTAAAGCACTAAATCGGAACCCTAAAGGGAGCCCCCGATTTAGAGCTTGACGGGGAAAGCCGGCGAACGTGGCGAGAAAGGAAGGGAAGAAAGCGAAAGGAGCGGGCGCTAGGGCGCTGGCAAGTGTAGCGGTCACGCTGCGCGTAACCACCACACCCGCCGCGCTTAATGCGCCGCTACAGGGCGCGTC"
        },
        {
          "sequenceDescription": "Synthetic construct plasmid pUB1395, complete sequence",
          "sequenceName": "MK178578.1", "sequence":
          "ACTGGCCGATAATTGCAGACGAACGGTGAGTAAGGAAAGAGTGAGGAACTATCGCATACCTGCATTTAAAGATGCTAGACTGA"
        },
        {
          "sequenceDescription": "Synthetic construct plasmid pUB1392, complete sequence",
          "sequenceName": "MK178577.1", "sequence": "CACAGATGCGTAAGGAGAAAATACCGCATCAGGAAATTGTAAACAATACCG"
        },
        {
          "sequenceDescription": "Synthetic construct plasmid pUB1375, complete sequence",
          "sequenceName": "MK178576.1", "sequence": "CACAGATGCGTAAGGAGAAAATACCGCATCAGGACCG"
        },
        {
          "sequenceDescription": "Synthetic construct plasmid pUB1004, complete sequence",
          "sequenceName": "MK178575.1", "sequence": "ACGCGGCCGCCAGCTGAAGCTTCGTACGCTGCAGGTCGGTGACACTATAGA"
        },
        {
          "sequenceDescription": "Synthetic construct plasmid pUB972, complete sequence",
          "sequenceName": "MK178574.1", "sequence": "CACAGATGCGTAAGGAGAAAATACCGCATATGCGGTGTGAAATACCG"
        },
        {
          "sequenceDescription": "Cloning vector pRSET6d (pBluescript KS plus derivative)",
          "sequenceName": "X54209.1", "sequence": "GATCTCGATCCCGCGAAATTAATCAG"
        },
      ],
      view: ''
    };
    // TODO: load sequences directly from JSON file:
      // sequenceArray = sequences[0].sequences;
      // console.log((sequenceArray[0].sequenceName));
    this.displayComponent = this.displayComponent.bind(this);
    this.handleClick = this.handleClick.bind(this);
    this.reorder = this.reorder.bind(this);
    this.updateSequences = this.updateSequences.bind(this);
  }
  displayComponent(view) {
    // selects components to render
    let _this = this;
    setTimeout( () => {
      switch (view) {
        case 'link-to-add':
          _this.setState({ view:
            <Add
              onSubmit={_this.updateSequences}
              loadedSequences={_this.state.loadedSequences}
            />
          });
          break;
        case 'link-to-sequences':
          _this.setState({ view:
            <Sequences
              loadedSequences={_this.state.loadedSequences}
              onReorder={_this.reorder}
            />
          });
          break;
        default:
          //
      }
    }, 0);
  }
  reorder(metadataProperty) {
    this.setState({ loadedSequences:
      this.state.loadedSequences.sort((a, b) =>
        a[metadataProperty].localeCompare(b[metadataProperty]))
    });
    this.displayComponent('link-to-sequences');
  }
  updateSequences(newSequence) {
    // adds uploaded sequence to the current runtime
    this.setState({ loadedSequences:
      [newSequence, ...this.state.loadedSequences]
    });
    this.displayComponent('link-to-sequences');
  }
  // Event Handlers
  handleClick(e) {
    switch (e.target.name) {
      case 'backToTop':
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
        break;
      default:
        this.displayComponent(e.target.id);
    }
  }
  // Lifecycle Methods
  componentDidMount() {
    this.displayComponent('link-to-sequences');
  }
  render() {
    return (
      <div>
        <header>
          <picture>
            <img src={"/img/logo.svg"} alt={"Double-helix icon"}/>
          </picture>
          <nav>
            <button onClick={this.handleClick} id={"link-to-add"}>Add New</button>
            <button onClick={this.handleClick} id={"link-to-sequences"}>View Sequences</button>
          </nav>
        </header>
        {this.state.view}
        <footer>
          <button onClick={this.handleClick} name="backToTop">
            Back to top
          </button>
          <div></div>
        </footer>
      </div>
    );
  }
}

export default App;
